### ISSUE TITLE
Website review (assignment 2)

### ISSUE THREAD

**Issue by Shirikara** [AdiBarnoor/AdiBarnoor.github.io#1]
Hey Adi! 
Nice to meet you 😊
I liked your repository and its clean and elegant design.
First, you have a small typo in: Weizmann **Istitute** of Science.
Also, I would merge the link text with the link URL so the text that appears is Weizmann Institute of Science and the URL where the URL link is embedded.
Lastly, as an option,  social media would be nice to add such as LinkedIn or Twitter (X).
See you in the class,
Shiri 

@liroh99

**Comment by AdiBarnoor** [comment]
Hi, thanks, I'll fix it
